"""Deterministic manufacturing engine for Custombuild."""

from typing import Any

from .artifact_limits import (
    MAX_API_TRANSIENT_BYTES,
    MAX_ARTIFACT_BYTES,
    MAX_CATALOG_SOURCE_BYTES,
    MAX_CORE_DOCUMENT_BYTES,
    MAX_EVIDENCE_ARTIFACTS,
    MAX_EVIDENCE_TOTAL_BYTES,
    MAX_HTTP_REQUEST_BYTES,
    MAX_PRODUCTION_BUNDLE_BYTES,
    MAX_READINESS_STATUS_BYTES,
    artifact_size_limit,
    valid_artifact_size,
)
from .dfm import (
    DFM_ENGINE_VERSION,
    STOCK_PROFILE_MISSING_CODE,
    STOCK_PROFILE_MISSING_MESSAGE,
    STOCK_PROFILE_MISSING_REQUIRED_ACTION,
    DFMValidator,
    stock_profile_missing_issue,
    validate_stock_profile_missing_issue,
)
from .errors import ArtifactError, ManufacturingError, NestingError, ProductionBlockedError
from .grain import (
    DFM_GRAIN_BLOCKER_CODE,
    DFM_GRAIN_REQUIRED_ACTION,
    DFM_GRAIN_RULE,
    DFM_GRAIN_RULE_MESSAGE,
    DFM_GRAIN_RULE_TITLE,
    DFM_GRAIN_RULE_VERSION,
    DFM_GRAIN_STOCK_MATCHED_PHASE,
    DFM_GRAIN_STOCK_SELECTION_INCOMPLETE_PHASE,
    GrainRuleDefinition,
    grain_control_projection,
    stock_grain_binding_issues,
    stock_grain_binding_required,
    validate_stock_grain_binding_issue,
)
from .model import (
    CAMOperation,
    DFMIssue,
    DFMReport,
    EdgeBandSpec,
    FeatureKind,
    MachineProfile,
    ManufacturingFeature,
    NestingLayout,
    OperationKind,
    OperationsDocument,
    PanelAxisMapping,
    PartInstance,
    PartSpec,
    Placement,
    Point2D,
    Rect,
    Setup,
    Severity,
    Side,
    StockSheet,
    ToolSpec,
    canonical_json_bytes,
    expand_part_instances,
    sha256_hex,
    um_to_mm,
)
from .nesting import DeterministicNester, validate_layout
from .operations import TwoSidedRegistration, generate_operations_document
from .package import (
    GENERATION_PLAN_ARTIFACT_PATH,
    GENERATION_PLAN_ARTIFACT_ROLE,
    GENERATION_PLAN_SCHEMA_VERSION,
    MANIFEST_CONTEXT_HASH_FIELDS,
    STOCK_SELECTION_SCHEMA_VERSION,
    ArtifactFile,
    ManifestContext,
    blocked_cam_artifact_violation,
    build_deterministic_zip,
    build_manifest,
    default_artifacts,
    design_review_artifacts,
    generation_plan_artifact,
    machine_profile_fingerprint,
    normalize_design_review_dfm_report,
    read_and_verify_package,
    stock_profiles_fingerprint,
    stock_selection_artifact,
    validate_design_review_status_dfm_report,
    validate_design_review_status_inventory_entries,
    validate_manifest_artifact_entries,
    validate_manifest_context_contract,
)
from .procurement import (
    GROUPED_BOM_SCHEMA_VERSION,
    STOCK_PURCHASE_SCHEMA_VERSION,
    grouped_bom_json,
    stock_purchase_csv,
)
from .profiles import linuxcnc_reference_router_1325, linuxcnc_reference_router_5125
from .quality import (
    LABEL_INDEX_SCHEMA_VERSION,
    QUALITY_MEASUREMENT_PLAN_SCHEMA_VERSION,
    label_index_csv,
    quality_measurement_plan_json,
)
from .readiness import (
    WORKSHOP_READINESS_SCHEMA_VERSION,
    ReadinessRequirement,
    ReadinessStatus,
    WorkshopReadinessReport,
    build_workshop_readiness_report,
    validate_workshop_evidence_binding,
)
from .review_status import (
    DADO_RETENTION_EVIDENCE_MISSING_BLOCKER_CODE,
    DESIGN_REVIEW_PACKAGE_STATUS_ARTIFACT_PATH,
    DESIGN_REVIEW_PACKAGE_STATUS_ARTIFACT_ROLE,
    DESIGN_REVIEW_PACKAGE_STATUS_SCHEMA_VERSION,
    CAMStageStatus,
    DesignReviewPackageStatus,
    blocked_design_review_package_status,
    dado_retention_evidence_missing,
    generated_design_review_package_status,
    joint_retention_contract_is_structurally_complete,
    normalize_design_review_package_status,
    validate_design_review_status_retention_binding,
)


def build_production_bundle(*args: Any, **kwargs: Any) -> Any:
    """Lazily load the cross-package production pipeline."""

    from .pipeline import build_production_bundle as build

    return build(*args, **kwargs)


__all__ = [
    "ArtifactError",
    "ArtifactFile",
    "MAX_ARTIFACT_BYTES",
    "MAX_API_TRANSIENT_BYTES",
    "MAX_CATALOG_SOURCE_BYTES",
    "MAX_CORE_DOCUMENT_BYTES",
    "MAX_EVIDENCE_ARTIFACTS",
    "MAX_EVIDENCE_TOTAL_BYTES",
    "MAX_PRODUCTION_BUNDLE_BYTES",
    "MAX_READINESS_STATUS_BYTES",
    "MAX_HTTP_REQUEST_BYTES",
    "CAMOperation",
    "CAMStageStatus",
    "DADO_RETENTION_EVIDENCE_MISSING_BLOCKER_CODE",
    "DESIGN_REVIEW_PACKAGE_STATUS_ARTIFACT_PATH",
    "DESIGN_REVIEW_PACKAGE_STATUS_ARTIFACT_ROLE",
    "DESIGN_REVIEW_PACKAGE_STATUS_SCHEMA_VERSION",
    "DFMReport",
    "DFMIssue",
    "DFM_ENGINE_VERSION",
    "DFM_GRAIN_BLOCKER_CODE",
    "DFM_GRAIN_REQUIRED_ACTION",
    "DFM_GRAIN_RULE",
    "DFM_GRAIN_RULE_MESSAGE",
    "DFM_GRAIN_STOCK_MATCHED_PHASE",
    "DFM_GRAIN_STOCK_SELECTION_INCOMPLETE_PHASE",
    "DFM_GRAIN_RULE_TITLE",
    "DFM_GRAIN_RULE_VERSION",
    "DFMValidator",
    "EdgeBandSpec",
    "DeterministicNester",
    "DesignReviewPackageStatus",
    "FeatureKind",
    "GENERATION_PLAN_ARTIFACT_PATH",
    "GENERATION_PLAN_ARTIFACT_ROLE",
    "GENERATION_PLAN_SCHEMA_VERSION",
    "GROUPED_BOM_SCHEMA_VERSION",
    "GrainRuleDefinition",
    "MachineProfile",
    "LABEL_INDEX_SCHEMA_VERSION",
    "ManifestContext",
    "MANIFEST_CONTEXT_HASH_FIELDS",
    "ManufacturingError",
    "ManufacturingFeature",
    "NestingError",
    "NestingLayout",
    "OperationKind",
    "OperationsDocument",
    "PanelAxisMapping",
    "PartInstance",
    "PartSpec",
    "Placement",
    "Point2D",
    "ProductionBlockedError",
    "QUALITY_MEASUREMENT_PLAN_SCHEMA_VERSION",
    "Rect",
    "Severity",
    "Setup",
    "Side",
    "StockSheet",
    "STOCK_PURCHASE_SCHEMA_VERSION",
    "STOCK_PROFILE_MISSING_CODE",
    "STOCK_PROFILE_MISSING_MESSAGE",
    "STOCK_PROFILE_MISSING_REQUIRED_ACTION",
    "STOCK_SELECTION_SCHEMA_VERSION",
    "ToolSpec",
    "TwoSidedRegistration",
    "WORKSHOP_READINESS_SCHEMA_VERSION",
    "ReadinessRequirement",
    "ReadinessStatus",
    "WorkshopReadinessReport",
    "build_deterministic_zip",
    "blocked_cam_artifact_violation",
    "build_manifest",
    "build_production_bundle",
    "artifact_size_limit",
    "build_workshop_readiness_report",
    "blocked_design_review_package_status",
    "dado_retention_evidence_missing",
    "canonical_json_bytes",
    "default_artifacts",
    "design_review_artifacts",
    "expand_part_instances",
    "generate_operations_document",
    "generated_design_review_package_status",
    "joint_retention_contract_is_structurally_complete",
    "generation_plan_artifact",
    "grain_control_projection",
    "grouped_bom_json",
    "linuxcnc_reference_router_1325",
    "linuxcnc_reference_router_5125",
    "machine_profile_fingerprint",
    "normalize_design_review_package_status",
    "normalize_design_review_dfm_report",
    "label_index_csv",
    "quality_measurement_plan_json",
    "read_and_verify_package",
    "sha256_hex",
    "stock_purchase_csv",
    "stock_profile_missing_issue",
    "stock_selection_artifact",
    "stock_profiles_fingerprint",
    "stock_grain_binding_issues",
    "stock_grain_binding_required",
    "um_to_mm",
    "validate_layout",
    "validate_stock_grain_binding_issue",
    "validate_stock_profile_missing_issue",
    "validate_design_review_status_inventory_entries",
    "validate_design_review_status_dfm_report",
    "validate_design_review_status_retention_binding",
    "validate_manifest_artifact_entries",
    "validate_manifest_context_contract",
    "validate_workshop_evidence_binding",
    "valid_artifact_size",
]
