packages:
  - apps/*
  - packages/*
overrides:
  "nanoid@<3.3.18": "3.3.18"
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@axe-core/playwright@4.13.0'
