"""Custombuild CAM validation primitives."""

from .model import MoveKind, RemovalEnvelope, ValidationBackplot, ValidationMove
from .production_model import (
    EXECUTABLE_CAM_CANDIDATE_MODE,
    MAX_LINUXCNC_TOOL_OR_OFFSET_NUMBER,
    MAX_THROUGH_OVERTRAVEL_UM,
    PRODUCTION_TOOLPATH_ENGINE_VERSION,
    PRODUCTION_TOOLPATH_SCHEMA_VERSION,
    BoundSetup,
    CuttingRecipe,
    ProductionCAMError,
    ProductionExecutionContext,
    ProductionMove,
    ProductionMoveKind,
    ProductionMoveRole,
    ProductionProgram,
    ProductionToolBinding,
    ProductionToolGeometry,
    ProductionToolpathDocument,
)
from .production_verification import (
    CUTTING_BACKPLOT_VERSION,
    CUTTING_PROGRAM_REPORT_SCHEMA_VERSION,
    CUTTING_PROGRAM_VERIFIER_VERSION,
    CuttingProgramIssue,
    CuttingProgramReport,
    CuttingProgramStatus,
    CuttingProgramVerification,
    SweptEnvelope,
    cutting_backplot_svg,
    cutting_program_report_json,
    verify_production_toolpaths,
)
from .toolpaths import depth_levels_um, generate_production_toolpaths
from .validation import (
    CAM_BACKPLOT_VERSION,
    CAM_VALIDATION_VERSION,
    CAMValidationError,
    CAMValidationResult,
    backplot_svg,
    build_validation_backplot,
    parse_operations_json,
    require_valid_operations,
    theoretical_removal_envelopes,
    validate_operations_document,
)

__all__ = [
    "CAM_BACKPLOT_VERSION",
    "CAM_VALIDATION_VERSION",
    "CAMValidationError",
    "CAMValidationResult",
    "CUTTING_BACKPLOT_VERSION",
    "CUTTING_PROGRAM_REPORT_SCHEMA_VERSION",
    "CUTTING_PROGRAM_VERIFIER_VERSION",
    "CuttingProgramIssue",
    "CuttingProgramReport",
    "CuttingProgramStatus",
    "CuttingProgramVerification",
    "EXECUTABLE_CAM_CANDIDATE_MODE",
    "MAX_THROUGH_OVERTRAVEL_UM",
    "MAX_LINUXCNC_TOOL_OR_OFFSET_NUMBER",
    "MoveKind",
    "PRODUCTION_TOOLPATH_ENGINE_VERSION",
    "PRODUCTION_TOOLPATH_SCHEMA_VERSION",
    "BoundSetup",
    "CuttingRecipe",
    "ProductionCAMError",
    "ProductionExecutionContext",
    "ProductionMove",
    "ProductionMoveKind",
    "ProductionMoveRole",
    "ProductionProgram",
    "ProductionToolBinding",
    "ProductionToolGeometry",
    "ProductionToolpathDocument",
    "RemovalEnvelope",
    "SweptEnvelope",
    "ValidationBackplot",
    "ValidationMove",
    "backplot_svg",
    "build_validation_backplot",
    "cutting_backplot_svg",
    "cutting_program_report_json",
    "depth_levels_um",
    "generate_production_toolpaths",
    "parse_operations_json",
    "require_valid_operations",
    "theoretical_removal_envelopes",
    "validate_operations_document",
    "verify_production_toolpaths",
]
