/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Check every dependency required to accept and complete application work.
         */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_v1_artifacts__artifact_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities/joints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Joint Capabilities
         * @description Expose the versioned support claim instead of implying enum-wide support.
         */
        get: operations["joint_capabilities_v1_capabilities_joints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Template Capabilities
         * @description Return server-owned support claims; client assertions are never trusted.
         */
        get: operations["template_capabilities_v1_capabilities_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/designs/autofix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autofix Design */
        post: operations["autofix_design_v1_designs_autofix_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/designs/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Design */
        post: operations["preview_design_v1_designs_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_v1_jobs__job_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Draft */
        get: operations["get_project_draft_v1_projects__project_id__draft_get"];
        /** Update Project Draft */
        put: operations["update_project_draft_v1_projects__project_id__draft_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List External Evidence */
        get: operations["list_external_evidence_v1_projects__project_id__evidence_get"];
        put?: never;
        /** Upload External Evidence */
        post: operations["upload_external_evidence_v1_projects__project_id__evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/imports/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect Import */
        post: operations["inspect_import_v1_projects__project_id__imports_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/production-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Production State
         * @description Return server-authoritative state for the project's current revision.
         *
         *     The web client may cache this response for responsiveness, but must use this
         *     endpoint to restore approvals, jobs and releases after reload or device
         *     changes. Returning an empty state for a project without revisions keeps the
         *     first production visit read-only and side-effect free.
         */
        get: operations["get_production_state_v1_projects__project_id__production_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_v1_projects__project_id__versions_get"];
        put?: never;
        /** Create Version */
        post: operations["create_version_v1_projects__project_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_v1_projects__project_id__versions__revision__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Version */
        post: operations["approve_version_v1_projects__project_id__versions__revision__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Version */
        post: operations["generate_version_v1_projects__project_id__versions__revision__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Version */
        post: operations["release_version_v1_projects__project_id__versions__revision__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Version */
        post: operations["validate_version_v1_projects__project_id__versions__revision__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}/workshop-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare Workshop Run
         * @description Prepare no physical state until a real executable package exists.
         *
         *     Clients can name only a generation job plus an explicit confirmation. The
         *     tenant revision, job result and release binding are resolved by the server;
         *     hashes, policies, machine identity and evidence cannot be supplied here.
         */
        post: operations["prepare_workshop_run_v1_projects__project_id__versions__revision__workshop_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases/{release_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Release Artifacts
         * @description List the exact package inventory frozen by a historical release.
         */
        get: operations["list_release_artifacts_v1_releases__release_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases/{release_id}/artifacts/{artifact_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Release Artifact
         * @description Stream an archived release without requiring it to be the current revision.
         */
        get: operations["download_release_artifact_v1_releases__release_id__artifacts__artifact_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalCreate */
        ApprovalCreate: {
            /**
             * Approval Type
             * @enum {string}
             */
            approval_type: "design" | "cam";
            /** Generation Job Id */
            generation_job_id?: string | null;
            /** Reason */
            reason: string;
            /** Warning Overrides */
            warning_overrides?: components["schemas"]["WarningOverrideCreate"][];
        };
        /**
         * ApprovalRead
         * @description Server-owned review state for restoring the production workflow.
         */
        ApprovalRead: {
            /**
             * Approval Type
             * @enum {string}
             */
            approval_type: "design" | "cam";
            /** Approved By */
            approved_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Generation Job Id */
            generation_job_id: string | null;
            /** Manifest Sha256 */
            manifest_sha256: string | null;
            /** Overrides Json */
            overrides_json: {
                [key: string]: unknown;
            }[];
            /** Production Context Hash */
            production_context_hash: string | null;
            /** Reason */
            reason: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ArtifactRead */
        ArtifactRead: {
            /** Content Type */
            content_type: string;
            /** Download Path */
            download_path: string;
            /** Download Url */
            download_url: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** Body_inspect_import_v1_projects__project_id__imports_inspect_post */
        Body_inspect_import_v1_projects__project_id__imports_inspect_post: {
            /** Document */
            document: string;
        };
        /** Body_upload_external_evidence_v1_projects__project_id__evidence_post */
        Body_upload_external_evidence_v1_projects__project_id__evidence_post: {
            /** Catalog Id */
            catalog_id: string;
            /** Catalog Version */
            catalog_version: string;
            /** Design Hash */
            design_hash: string;
            /** Document */
            document: string;
            /**
             * Evidence Type
             * @enum {string}
             */
            evidence_type: "wall_anchor" | "hardware" | "material_grain" | "joint_retention";
            /** Expires At */
            expires_at?: string | null;
            /** Rule Id */
            rule_id: string;
        };
        /** BookcasePreviewInput */
        BookcasePreviewInput: {
            /**
             * Back Material Id
             * @description Optional exact 6 mm back-panel material. When omitted, legacy clients retain the matching MDF/birch-plywood derivation from material_id.
             */
            back_material_id?: ("mdf-6" | "birch-plywood-6") | null;
            /**
             * Back Panel
             * @default true
             */
            back_panel: boolean | ("none" | "surface_mounted" | "inset_groove");
            /**
             * Base Cabinet Count
             * @default 0
             */
            base_cabinet_count: number;
            /**
             * Base Cabinet Depth Mm
             * @default 0
             */
            base_cabinet_depth_mm: number;
            /**
             * Base Cabinet Height Mm
             * @default 0
             */
            base_cabinet_height_mm: number;
            /** Bay Width Ratios */
            bay_width_ratios?: number[];
            /**
             * Depth Mm
             * @default 320
             */
            depth_mm: number;
            /**
             * Divider Count
             * @default 0
             */
            divider_count: number;
            /**
             * Edge Band Mm
             * @default 1
             */
            edge_band_mm: number;
            /**
             * Furniture Type
             * @default bookcase
             * @enum {string}
             */
            furniture_type: "bookcase" | "wall_library";
            /**
             * Height Mm
             * @default 2000
             */
            height_mm: number;
            /**
             * Joint System
             * @description Only DADO has an implemented deterministic design-review path in the MVP. CAM remains conditional on authenticated retention evidence and all other manufacturing gates; other joint types are capability-blocked.
             * @default dado
             * @constant
             */
            joint_system: "dado";
            /**
             * Load Per Shelf Kg
             * @default 30
             */
            load_per_shelf_kg: number;
            /**
             * Material Id
             * @default mdf
             * @enum {string}
             */
            material_id: "mdf" | "birch-plywood";
            /**
             * Measured Thickness Mm
             * @description MVP catalogue range for nominal 18 mm carcass sheet material.
             * @default 18
             */
            measured_thickness_mm: number;
            /**
             * Nominal Thickness Mm
             * @description The production MVP catalogue contains nominal 18 mm carcass sheets.
             * @default 18
             */
            nominal_thickness_mm: number;
            /**
             * Plinth
             * @default true
             */
            plinth: boolean;
            /** Plinth Height Mm */
            plinth_height_mm?: number | null;
            /**
             * Reinforcement Mode
             * @default manual
             * @enum {string}
             */
            reinforcement_mode: "manual" | "auto";
            /**
             * Shelf Count
             * @default 5
             */
            shelf_count: number;
            /** Shelf Height Ratios */
            shelf_height_ratios?: number[];
            /**
             * Shelf Mount
             * @default fixed
             * @enum {string}
             */
            shelf_mount: "fixed" | "adjustable";
            /**
             * Wall Anchor Required
             * @default false
             */
            wall_anchor_required: boolean;
            /**
             * Wall Anchor Verified
             * @default false
             */
            wall_anchor_verified: boolean;
            /**
             * Width Mm
             * @default 900
             */
            width_mm: number;
        };
        /**
         * DesignStatus
         * @enum {string}
         */
        DesignStatus: "concept" | "draft" | "design_validated" | "cam_validated" | "approved" | "released" | "superseded" | "archived";
        /** DesignVersionCreate */
        DesignVersionCreate: {
            /** Expected Current Revision */
            expected_current_revision: number;
            /** Expected Design Hash */
            expected_design_hash: string;
            /**
             * Joint Retention Evidence Id
             * @description Optional immutable signed retention statement. The server verifies and injects the resulting contract; clients never submit contract fields.
             */
            joint_retention_evidence_id?: string | null;
            production_context: components["schemas"]["RevisionProductionContext"];
            source_provenance?: components["schemas"]["ReferenceImageSourceProvenance"] | null;
            spec: components["schemas"]["BookcasePreviewInput"];
            /** Template Id */
            template_id: string;
        };
        /** DesignVersionRead */
        DesignVersionRead: {
            /** Context Hash */
            context_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Design Hash */
            design_hash: string;
            /** Engine Version */
            engine_version: string;
            /** Id */
            id: string;
            /** Immutable */
            immutable: boolean;
            /** Project Id */
            project_id: string;
            /** Result Json */
            result_json: {
                [key: string]: unknown;
            };
            /** Revision */
            revision: number;
            /** Rule Version */
            rule_version: string;
            /** Source Import Id */
            source_import_id: string | null;
            /** Source Provenance Json */
            source_provenance_json: {
                [key: string]: unknown;
            };
            /** Spec Json */
            spec_json: {
                [key: string]: unknown;
            };
            status: components["schemas"]["DesignStatus"];
            /** Template Capability Fingerprint */
            template_capability_fingerprint: string;
            /** Template Id */
            template_id: string;
            /** Template Version */
            template_version: string;
        };
        /** ExternalEvidenceRead */
        ExternalEvidenceRead: {
            /** Catalog Id */
            catalog_id: string;
            /** Catalog Version */
            catalog_version: string;
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Design Hash */
            design_hash: string;
            /**
             * Evidence Type
             * @enum {string}
             */
            evidence_type: "wall_anchor" | "hardware" | "material_grain" | "joint_retention";
            /** Expires At */
            expires_at: string | null;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Rule Id */
            rule_id: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** GenerationRequest */
        GenerationRequest: {
            /**
             * Back Stock Count
             * @default 2
             */
            back_stock_count: number;
            /**
             * Back Stock Height Mm
             * @default 1220
             */
            back_stock_height_mm: number;
            /**
             * Back Stock Width Mm
             * @default 2440
             */
            back_stock_width_mm: number;
            /** External Evidence Ids */
            external_evidence_ids?: string[];
            /**
             * Include Freecad Project
             * @default false
             */
            include_freecad_project: boolean;
            /**
             * Include Step
             * @default true
             */
            include_step: boolean;
            /**
             * Include Validation Program
             * @default true
             */
            include_validation_program: boolean;
            /**
             * Machine Profile Id
             * @default custombuild-router-1325-linuxcnc
             * @enum {string}
             */
            machine_profile_id: "custombuild-router-1325-linuxcnc" | "custombuild-router-5125-linuxcnc";
            /**
             * Postprocessor Id
             * @default linuxcnc-validation-1.1.0
             * @constant
             */
            postprocessor_id: "linuxcnc-validation-1.1.0";
            /**
             * Stock Count
             * @default 4
             */
            stock_count: number;
            /**
             * Stock Height Mm
             * @default 1220
             */
            stock_height_mm: number;
            /**
             * Stock Width Mm
             * @default 2440
             */
            stock_width_mm: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportInspection */
        ImportInspection: {
            /** Assumptions */
            assumptions: {
                [key: string]: unknown;
            }[];
            /** Furniture Type */
            furniture_type: "bookcase" | null;
            /** Furniture Type Confidence */
            furniture_type_confidence: number;
            /** Image Sha256 */
            image_sha256: string;
            /** Import Id */
            import_id: string;
            /** Media Type */
            media_type: string;
            /** Project Id */
            project_id: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Status
             * @constant
             */
            status: "needs_calibration";
            /** Unknown Fields */
            unknown_fields: string[];
        };
        /** JobRead */
        JobRead: {
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deadline At */
            deadline_at: string | null;
            /** Design Version Id */
            design_version_id: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Next Attempt At */
            next_attempt_at: string | null;
            /** Production Context Hash */
            production_context_hash: string;
            /** Production Engine Context Json */
            production_engine_context_json: {
                [key: string]: unknown;
            };
            /** Result Json */
            result_json: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["JobStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * ProductionStateRead
         * @description Complete recoverable state for the current project revision.
         */
        ProductionStateRead: {
            /** Approvals */
            approvals: components["schemas"]["ApprovalRead"][];
            latest_job: components["schemas"]["JobRead"] | null;
            /** Project Id */
            project_id: string;
            release: components["schemas"]["ReleaseRead"] | null;
            version: components["schemas"]["DesignVersionRead"] | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Furniture Type
             * @default bookcase
             * @constant
             */
            furniture_type: "bookcase";
            /** Name */
            name: string;
        };
        /** ProjectDraftRead */
        ProjectDraftRead: {
            /** Design Hash */
            design_hash: string | null;
            /** Draft Revision */
            draft_revision: number;
            /** Project Id */
            project_id: string;
            /** Result Json */
            result_json: {
                [key: string]: unknown;
            } | null;
            /** Spec Json */
            spec_json: {
                [key: string]: unknown;
            } | null;
            /** Template Id */
            template_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workspace Spec Json */
            workspace_spec_json: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ProjectDraftUpdate
         * @description A mutable workspace draft with a bounded, versioned UI-intent envelope.
         */
        ProjectDraftUpdate: {
            /** Expected Draft Revision */
            expected_draft_revision: number;
            spec: components["schemas"]["BookcasePreviewInput"];
            /** Template Id */
            template_id: string;
            workspace_spec: components["schemas"]["WorkspaceIntentV1"];
        };
        /** ProjectRead */
        ProjectRead: {
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Revision */
            current_revision: number;
            /** Description */
            description: string;
            /** Furniture Type */
            furniture_type: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReferenceImageConfirmedInputs */
        ReferenceImageConfirmedInputs: {
            /**
             * Construction Assumptions Confirmed
             * @constant
             */
            construction_assumptions_confirmed: true;
            /**
             * Dimensions Measured
             * @constant
             */
            dimensions_measured: true;
            /**
             * Layout Confirmed
             * @constant
             */
            layout_confirmed: true;
            /**
             * Material Confirmed
             * @constant
             */
            material_confirmed: true;
        };
        /** ReferenceImageSourceProvenance */
        ReferenceImageSourceProvenance: {
            /** Confidence */
            confidence: number;
            confirmed_inputs: components["schemas"]["ReferenceImageConfirmedInputs"];
            /** Detected Base Cabinets */
            detected_base_cabinets: boolean;
            /** Detected Dividers */
            detected_dividers: number;
            /** Detected Shelves */
            detected_shelves: number;
            /** File Name */
            file_name: string;
            /** Image Height Px */
            image_height_px: number;
            /** Image Sha256 */
            image_sha256: string;
            /** Image Width Px */
            image_width_px: number;
            /** Import Id */
            import_id: string;
            /**
             * Source
             * @constant
             */
            source: "reference_image";
            /**
             * Verification Status
             * @constant
             */
            verification_status: "parametric_confirmed";
            /** Verified Model Fingerprint */
            verified_model_fingerprint: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * ReleaseArtifactRead
         * @description One immutable artifact resolved through its historical release.
         */
        ReleaseArtifactRead: {
            /** Content Type */
            content_type: string;
            /** Download Path */
            download_path: string;
            /** Download Url */
            download_url: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Release Id */
            release_id: string;
            /** Release Number */
            release_number: string;
            /** Revision */
            revision: number;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ReleaseCreate */
        ReleaseCreate: {
            /**
             * Confirmation
             * @constant
             */
            confirmation: "RELEASE";
            /** Release Number */
            release_number: string;
        };
        /** ReleaseRead */
        ReleaseRead: {
            /**
             * Machine Use
             * @constant
             */
            machine_use: "validation_only";
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** Release Id */
            release_id: string;
            /**
             * Release Kind
             * @constant
             */
            release_kind: "design_review";
            /** Release Number */
            release_number: string;
            /**
             * Status
             * @constant
             */
            status: "released";
        };
        /**
         * RevisionProductionContext
         * @description Production-affecting choices frozen when a design revision is created.
         */
        RevisionProductionContext: {
            /** Back Stock Count */
            back_stock_count: number;
            /** Back Stock Height Mm */
            back_stock_height_mm: number;
            /** Back Stock Width Mm */
            back_stock_width_mm: number;
            /** Machine Profile Id */
            machine_profile_id: string;
            /** Stock Count */
            stock_count: number;
            /** Stock Height Mm */
            stock_height_mm: number;
            /** Stock Width Mm */
            stock_width_mm: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WarningOverrideCreate */
        WarningOverrideCreate: {
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Reason */
            reason: string;
            /** Rule Id */
            rule_id: string;
        };
        /** WorkshopRunBlockedResponse */
        WorkshopRunBlockedResponse: {
            detail: components["schemas"]["WorkshopRunBlockerDetail"];
        };
        /**
         * WorkshopRunBlockerDetail
         * @description Truthful current-state result for the blocker-only workshop endpoint.
         */
        WorkshopRunBlockerDetail: {
            /**
             * Code
             * @enum {string}
             */
            code: "EXECUTABLE_MACHINE_PROGRAM_MISSING" | "WORKSHOP_EXECUTABLE_PACKAGE_MISSING" | "WORKSHOP_GENERATION_JOB_NOT_READY";
            /** Cutting Blocker Codes */
            cutting_blocker_codes: [
                "EXECUTABLE_MACHINE_PROGRAM_MISSING" | "WORKSHOP_EXECUTABLE_PACKAGE_MISSING" | "WORKSHOP_GENERATION_JOB_NOT_READY"
            ];
            /** Message */
            message: string;
            /**
             * Physical Cutting Authorized
             * @constant
             */
            physical_cutting_authorized: false;
            /**
             * Release Review Eligible
             * @constant
             */
            release_review_eligible: false;
            /** Solution */
            solution: string;
            /**
             * Workshop Status
             * @constant
             */
            workshop_status: "BLOCKED";
        };
        /**
         * WorkshopRunPrepare
         * @description Non-authoritative request to prepare one server-derived workshop run.
         */
        WorkshopRunPrepare: {
            /**
             * Confirmation
             * @constant
             */
            confirmation: "PREPARE_WORKSHOP_RUN";
            /** Generation Job Id */
            generation_job_id: string;
        };
        /** WorkspaceIntentV1 */
        WorkspaceIntentV1: {
            /**
             * Bay Sizing Mode
             * @enum {string}
             */
            bay_sizing_mode: "count" | "target_width";
            /** Part Overrides */
            part_overrides: {
                [key: string]: components["schemas"]["WorkspacePartOverride"];
            };
            production_context: components["schemas"]["WorkspaceProductionContext"];
            /** Reference Image Import */
            reference_image_import?: components["schemas"]["WorkspaceReferenceImageImport"];
            /** Removed Part Ids */
            removed_part_ids: string[];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "custombuild.workspace-intent.v1";
            /** Symmetry Locked */
            symmetry_locked: boolean;
            /** Target Bay Width Mm */
            target_bay_width_mm: number;
            /** Topology Baseline */
            topology_baseline?: components["schemas"]["WorkspaceTopologyBaseline"];
        };
        /** WorkspacePartOverride */
        WorkspacePartOverride: {
            /** Depth Mm */
            depth_mm?: number;
            /** Position X Mm */
            position_x_mm?: number;
            /** Position Y Mm */
            position_y_mm?: number;
            /** Position Z Mm */
            position_z_mm?: number;
            /** Thickness Mm */
            thickness_mm?: number;
            /** Width Mm */
            width_mm?: number;
        };
        /** WorkspaceProductionContext */
        WorkspaceProductionContext: {
            /** Back Stock Count */
            back_stock_count: number;
            /** Back Stock Height Mm */
            back_stock_height_mm: number;
            /** Back Stock Width Mm */
            back_stock_width_mm: number;
            /**
             * Machine Profile Id
             * @enum {string}
             */
            machine_profile_id: "custombuild-router-1325-linuxcnc" | "custombuild-router-5125-linuxcnc";
            /** Stock Count */
            stock_count: number;
            /** Stock Height Mm */
            stock_height_mm: number;
            /** Stock Width Mm */
            stock_width_mm: number;
        };
        /** WorkspaceReferenceConfirmedInputs */
        WorkspaceReferenceConfirmedInputs: {
            /** Construction Assumptions Confirmed */
            construction_assumptions_confirmed: boolean;
            /** Dimensions Measured */
            dimensions_measured: boolean;
            /** Layout Confirmed */
            layout_confirmed: boolean;
            /** Material Confirmed */
            material_confirmed: boolean;
        };
        /** WorkspaceReferenceImageImport */
        WorkspaceReferenceImageImport: {
            /** Confidence */
            confidence: number;
            confirmed_inputs?: components["schemas"]["WorkspaceReferenceConfirmedInputs"];
            /** Detected Base Cabinets */
            detected_base_cabinets: boolean;
            /** Detected Dividers */
            detected_dividers: number;
            /** Detected Shelves */
            detected_shelves: number;
            /** File Name */
            file_name: string;
            /** Image Height Px */
            image_height_px: number;
            /** Image Sha256 */
            image_sha256: string;
            /** Image Width Px */
            image_width_px: number;
            /** Import Id */
            import_id: string;
            /**
             * Source
             * @constant
             */
            source: "reference_image";
            /**
             * Verification Status
             * @default concept
             * @enum {string}
             */
            verification_status: "concept" | "parametric_confirmed";
            /** Verified Model Fingerprint */
            verified_model_fingerprint?: string;
            /** Warnings */
            warnings: string[];
        };
        /** WorkspaceTopologyBaseline */
        WorkspaceTopologyBaseline: {
            /** Base Cabinet Count */
            base_cabinet_count: number;
            /** Bay Width Ratios */
            bay_width_ratios: number[];
            /** Divider Count */
            divider_count: number;
            /**
             * Reinforcement Mode
             * @enum {string}
             */
            reinforcement_mode: "manual" | "auto";
            /** Shelf Count */
            shelf_count: number;
            /** Shelf Height Ratios */
            shelf_height_ratios: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    download_artifact_v1_artifacts__artifact_id__download_get: {
        parameters: {
            query: {
                expires: number;
                signature: string;
            };
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fully verified artifact bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    joint_capabilities_v1_capabilities_joints_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    template_capabilities_v1_capabilities_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    autofix_design_v1_designs_autofix_post: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookcasePreviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_design_v1_designs_preview_post: {
        parameters: {
            query?: {
                project_id?: string | null;
                joint_retention_evidence_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookcasePreviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_v1_jobs__job_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_projects_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    create_project_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_draft_v1_projects__project_id__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_draft_v1_projects__project_id__draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectDraftUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_external_evidence_v1_projects__project_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalEvidenceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_external_evidence_v1_projects__project_id__evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_external_evidence_v1_projects__project_id__evidence_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalEvidenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_import_v1_projects__project_id__imports_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_inspect_import_v1_projects__project_id__imports_inspect_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportInspection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_production_state_v1_projects__project_id__production_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionStateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_v1_projects__project_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_v1_projects__project_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesignVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_v1_projects__project_id__versions__revision__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_version_v1_projects__project_id__versions__revision__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_version_v1_projects__project_id__versions__revision__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_version_v1_projects__project_id__versions__revision__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_version_v1_projects__project_id__versions__revision__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_workshop_run_v1_projects__project_id__versions__revision__workshop_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkshopRunPrepare"];
            };
        };
        responses: {
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The active role lacks workshop preparation capability. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The tenant-scoped project or revision was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server-owned generation/release is not an immutable executable workshop package. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkshopRunBlockedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_release_artifacts_v1_releases__release_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseArtifactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_release_artifact_v1_releases__release_id__artifacts__artifact_id__download_get: {
        parameters: {
            query: {
                expires: number;
                signature: string;
            };
            header?: never;
            path: {
                release_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fully verified immutable release artifact bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
