/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_v1_artifacts__artifact_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities/joints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Joint Capabilities
         * @description Expose the versioned support claim instead of implying enum-wide support.
         */
        get: operations["joint_capabilities_v1_capabilities_joints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/designs/autofix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autofix Design */
        post: operations["autofix_design_v1_designs_autofix_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/designs/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Design */
        post: operations["preview_design_v1_designs_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/imports/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect Import */
        post: operations["inspect_import_v1_imports_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_v1_jobs__job_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_v1_projects__project_id__versions_get"];
        put?: never;
        /** Create Version */
        post: operations["create_version_v1_projects__project_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_v1_projects__project_id__versions__revision__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Version */
        post: operations["approve_version_v1_projects__project_id__versions__revision__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Version */
        post: operations["generate_version_v1_projects__project_id__versions__revision__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Version */
        post: operations["release_version_v1_projects__project_id__versions__revision__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}/versions/{revision}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Version */
        post: operations["validate_version_v1_projects__project_id__versions__revision__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalCreate */
        ApprovalCreate: {
            /**
             * Approval Type
             * @enum {string}
             */
            approval_type: "design" | "cam";
            /** Generation Job Id */
            generation_job_id?: string | null;
            /** Reason */
            reason: string;
            /** Warning Overrides */
            warning_overrides?: components["schemas"]["WarningOverrideCreate"][];
        };
        /** ArtifactRead */
        ArtifactRead: {
            /** Content Type */
            content_type: string;
            /** Download Path */
            download_path: string;
            /** Download Url */
            download_url: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** Body_inspect_import_v1_imports_inspect_post */
        Body_inspect_import_v1_imports_inspect_post: {
            /**
             * Document
             * Format: binary
             */
            document: string;
        };
        /** BookcasePreviewInput */
        BookcasePreviewInput: {
            /**
             * Back Panel
             * @default true
             */
            back_panel: boolean | ("none" | "surface_mounted" | "inset_groove");
            /**
             * Depth Mm
             * @default 320
             */
            depth_mm: number;
            /**
             * Divider Count
             * @default 0
             */
            divider_count: number;
            /**
             * Edge Band Mm
             * @default 1
             */
            edge_band_mm: number;
            /**
             * Height Mm
             * @default 2000
             */
            height_mm: number;
            /**
             * Joint System
             * @description Only DADO has a verified domain-to-CAM-to-assembly path in the production MVP. Other catalogue joint types are explicitly capability-blocked.
             * @default dado
             * @constant
             */
            joint_system: "dado";
            /**
             * Load Per Shelf Kg
             * @default 30
             */
            load_per_shelf_kg: number;
            /**
             * Material Id
             * @default mdf
             * @enum {string}
             */
            material_id: "mdf" | "birch-plywood";
            /**
             * Measured Thickness Mm
             * @description MVP catalogue range for nominal 18 mm carcass sheet material.
             * @default 18
             */
            measured_thickness_mm: number;
            /**
             * Nominal Thickness Mm
             * @description The production MVP catalogue contains nominal 18 mm carcass sheets.
             * @default 18
             */
            nominal_thickness_mm: number;
            /**
             * Plinth
             * @default true
             */
            plinth: boolean;
            /** Plinth Height Mm */
            plinth_height_mm?: number | null;
            /**
             * Reinforcement Mode
             * @default manual
             * @enum {string}
             */
            reinforcement_mode: "manual" | "auto";
            /**
             * Shelf Count
             * @default 5
             */
            shelf_count: number;
            /**
             * Shelf Mount
             * @default fixed
             * @enum {string}
             */
            shelf_mount: "fixed" | "adjustable";
            /**
             * Wall Anchor Required
             * @default false
             */
            wall_anchor_required: boolean;
            /**
             * Wall Anchor Verified
             * @default false
             */
            wall_anchor_verified: boolean;
            /**
             * Width Mm
             * @default 900
             */
            width_mm: number;
        };
        /**
         * DesignStatus
         * @enum {string}
         */
        DesignStatus: "concept" | "draft" | "design_validated" | "cam_validated" | "approved" | "released" | "superseded" | "archived";
        /** DesignVersionCreate */
        DesignVersionCreate: {
            spec: components["schemas"]["BookcasePreviewInput"];
        };
        /** DesignVersionRead */
        DesignVersionRead: {
            /** Context Hash */
            context_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Design Hash */
            design_hash: string;
            /** Engine Version */
            engine_version: string;
            /** Id */
            id: string;
            /** Immutable */
            immutable: boolean;
            /** Project Id */
            project_id: string;
            /** Result Json */
            result_json: {
                [key: string]: unknown;
            };
            /** Revision */
            revision: number;
            /** Rule Version */
            rule_version: string;
            /** Spec Json */
            spec_json: {
                [key: string]: unknown;
            };
            status: components["schemas"]["DesignStatus"];
            /** Template Version */
            template_version: string;
        };
        /** GenerationRequest */
        GenerationRequest: {
            /**
             * Back Stock Count
             * @default 2
             */
            back_stock_count: number;
            /**
             * Back Stock Height Mm
             * @default 1220
             */
            back_stock_height_mm: number;
            /**
             * Back Stock Width Mm
             * @default 2440
             */
            back_stock_width_mm: number;
            /**
             * Include Step
             * @default true
             */
            include_step: boolean;
            /**
             * Include Validation Program
             * @default true
             */
            include_validation_program: boolean;
            /**
             * Machine Profile Id
             * @default custombuild-router-1325-linuxcnc
             */
            machine_profile_id: string;
            /**
             * Postprocessor Id
             * @default linuxcnc-validation-1.0.0
             */
            postprocessor_id: string;
            /**
             * Stock Count
             * @default 4
             */
            stock_count: number;
            /**
             * Stock Height Mm
             * @default 1220
             */
            stock_height_mm: number;
            /**
             * Stock Width Mm
             * @default 2440
             */
            stock_width_mm: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportInspection */
        ImportInspection: {
            /** Assumptions */
            assumptions: {
                [key: string]: unknown;
            }[];
            /** Furniture Type */
            furniture_type: "bookcase" | null;
            /** Furniture Type Confidence */
            furniture_type_confidence: number;
            /** Import Id */
            import_id: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Status
             * @constant
             */
            status: "needs_calibration";
            /** Unknown Fields */
            unknown_fields: string[];
        };
        /** JobRead */
        JobRead: {
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Design Version Id */
            design_version_id: string;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Production Context Hash */
            production_context_hash: string;
            /** Production Engine Context Json */
            production_engine_context_json: {
                [key: string]: unknown;
            };
            /** Result Json */
            result_json: {
                [key: string]: unknown;
            } | null;
            status: components["schemas"]["JobStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** ProjectCreate */
        ProjectCreate: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Furniture Type
             * @default bookcase
             * @constant
             */
            furniture_type: "bookcase";
            /** Name */
            name: string;
        };
        /** ProjectRead */
        ProjectRead: {
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Revision */
            current_revision: number;
            /** Description */
            description: string;
            /** Furniture Type */
            furniture_type: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReleaseCreate */
        ReleaseCreate: {
            /**
             * Confirmation
             * @constant
             */
            confirmation: "RELEASE";
            /** Release Number */
            release_number: string;
        };
        /** ReleaseRead */
        ReleaseRead: {
            /**
             * Machine Use
             * @constant
             */
            machine_use: "validation_only";
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** Release Id */
            release_id: string;
            /** Release Number */
            release_number: string;
            /**
             * Status
             * @constant
             */
            status: "released";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WarningOverrideCreate */
        WarningOverrideCreate: {
            /** Reason */
            reason: string;
            /** Rule Id */
            rule_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    download_artifact_v1_artifacts__artifact_id__download_get: {
        parameters: {
            query: {
                expires: number;
                signature: string;
            };
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    joint_capabilities_v1_capabilities_joints_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    autofix_design_v1_designs_autofix_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookcasePreviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_design_v1_designs_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookcasePreviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_import_v1_imports_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_inspect_import_v1_imports_inspect_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportInspection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_v1_jobs__job_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_projects_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    create_project_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_v1_projects__project_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_v1_projects__project_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesignVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_v1_projects__project_id__versions__revision__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_version_v1_projects__project_id__versions__revision__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_version_v1_projects__project_id__versions__revision__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_version_v1_projects__project_id__versions__revision__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_version_v1_projects__project_id__versions__revision__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                revision: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
