"""Public, framework-independent domain API for Custombuild."""

from .engine import BookcaseEngine, build_bookcase
from .enums import (
    AssemblyDirection,
    BackPanelType,
    DesignStatus,
    FaceName,
    FeatureKind,
    GrainDirection,
    JointType,
    MaterialType,
    PartRole,
    ReinforcementMode,
    ShelfMount,
)
from .identity import canonical_json, content_hash, stable_id
from .materials import (
    screening_birch_plywood_6,
    screening_birch_plywood_18,
    screening_mdf_6,
    screening_mdf_18,
)
from .models import (
    BOOKCASE_ENGINE_VERSION,
    BOOKCASE_TEMPLATE_VERSION,
    AssemblyEdge,
    AssemblyGraph,
    AssemblyNode,
    AssemblyStep,
    BookcaseDesignSpec,
    BookcaseParameters,
    DesignResult,
    Dimensions3D,
    EdgeBand,
    FeatureDimensions,
    FrozenModel,
    Joint,
    JointMember,
    ManufacturingFeature,
    MaterialVersion,
    PartInstance,
    Placement,
    Point3D,
    PropertySource,
    WallAnchorSpec,
)
from .support import (
    BOOKCASE_JOINT_SUPPORT_MATRIX,
    BOOKCASE_JOINT_SUPPORT_VERSION,
    SUPPORTED_BOOKCASE_PRIMARY_JOINTS,
    WEIGHT_BASIS,
    joint_support_payload,
)
from .units import UM_PER_M, UM_PER_MM, metres, mm, to_mm

__all__ = [
    "UM_PER_M",
    "UM_PER_MM",
    "AssemblyDirection",
    "AssemblyEdge",
    "AssemblyGraph",
    "AssemblyNode",
    "AssemblyStep",
    "BackPanelType",
    "BookcaseDesignSpec",
    "BookcaseEngine",
    "BookcaseParameters",
    "BOOKCASE_JOINT_SUPPORT_MATRIX",
    "BOOKCASE_JOINT_SUPPORT_VERSION",
    "BOOKCASE_ENGINE_VERSION",
    "BOOKCASE_TEMPLATE_VERSION",
    "DesignResult",
    "DesignStatus",
    "Dimensions3D",
    "EdgeBand",
    "FaceName",
    "FeatureDimensions",
    "FeatureKind",
    "FrozenModel",
    "GrainDirection",
    "Joint",
    "JointMember",
    "JointType",
    "ManufacturingFeature",
    "MaterialType",
    "MaterialVersion",
    "PartInstance",
    "PartRole",
    "Placement",
    "Point3D",
    "PropertySource",
    "ReinforcementMode",
    "ShelfMount",
    "SUPPORTED_BOOKCASE_PRIMARY_JOINTS",
    "WEIGHT_BASIS",
    "WallAnchorSpec",
    "build_bookcase",
    "canonical_json",
    "content_hash",
    "joint_support_payload",
    "metres",
    "mm",
    "screening_birch_plywood_18",
    "screening_birch_plywood_6",
    "screening_mdf_6",
    "screening_mdf_18",
    "stable_id",
    "to_mm",
]
